### ISSUE TITLE
Cannot read properties of undefined (reading 'cbid')

### ISSUE THREAD

**Issue by klessed** [Argonne-National-Laboratory/node-red-contrib-ocpp#58]
Hi,

After upgrading to version 1.3.5 I get following error and node-red restarts due to an Uncaught Exception:
[error] TypeError: Cannot read properties of undefined (reading 'cbid')
    at WebSocketServer.connection (/data/node_modules/node-red-contrib-ocpp/ocpp/ocpp-server.js:226:58)
    at WebSocketServer.emit (node:events:525:35)
    at WebSocketServer.completeUpgrade (/data/node_modules/ws/lib/websocket-server.js:358:5)
    at WebSocketServer.handleUpgrade (/data/node_modules/ws/lib/websocket-server.js:271:10)
    at Server.upgrade (/data/node_modules/ws/lib/websocket-server.js:107:16)
    at Server.emit (node:events:513:28)
    at onParserExecuteCommon (node:_http_server:772:14)
    at onParserExecute (node:_http_server:686:3)

**Comment by jshaw-delta** [comment]
Having the same issue - tried with both simulators and with real EV chargers.

**Comment by bnystrom** [comment]
The server thinks it is missing the chargebox id in the connection route. Can you verify that one is being sent?

The OCPP CS server connection should look something like:

ws://my.ocppserver.com:1234/ocpp2/evse1

(the important part here is the last part)
Can you verify that you are not trying to connect without the chargebox Id?
( wrong: ws://my.ocppserver.com:1234/ocpp2)

**Comment by bjornreppen** [comment]
I am also experiencing the same.  
Running node-red in docker from 'nodered/node-red'.  
node-red-contric-ocpp version 1.3.5
Connecting from a Wallbox pulsar max.

The request href is '/ocpp16s/garage/.websocket'.  
req.params is undefined, not even an empty object.

**Comment by bnystrom** [comment]
It appears that some EVSEs may attempt to connect initially to the base URL. The server now ignores those requests unless the path is valid. Updating in release 1.3.6

**Comment by klessed** [comment]
This seems to work
